name: module_business
description: A new Flutter package project.
version: 0.0.1
homepage: none
publish_to: none

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  module_data:
    path: ../module_data

  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
